/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.autor;

import communication.KomunikacijaSaServerom;
import domenn.Autor;
import domenn.Radnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import konstante.IOperacije;
import konstante.IStatus;
import transfer.OdgovorObjekat;
import transfer.ZahtevObjekat;

/**
 *
 * @author Djordje Vukicevic
 */
public class FrmKreiranjeAutora extends javax.swing.JPanel {

    private Radnik ulogovaniRadnik;
    private Autor autor;

    /**
     * Creates new form FrmKreiranjeAutora
     */
    public FrmKreiranjeAutora() {
        initComponents();
        jButtonIzmeni.setVisible(false);
    }

    public FrmKreiranjeAutora(Autor a) {
        autor = a;
        initComponents();
        jButtonSacuvaj.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovaniRadnik = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelJMBG = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldZanr = new javax.swing.JTextField();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();

        jLabelUlogovaniRadnik.setText("Ulogovani radnik:");

        jLabelIme.setText("Ime: ");

        jLabelPrezime.setText("Prezime: ");

        jLabelJMBG.setText("Zanr :");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUlogovaniRadnik)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelJMBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSacuvaj)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOdustani))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldZanr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelUlogovaniRadnik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIme)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezime)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJMBG)
                    .addComponent(jTextFieldZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvaj)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonIzmeni))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        if (jTextFieldIme.getText().isEmpty() || jTextFieldPrezime.getText().isEmpty()
                || jTextFieldZanr.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Morate popuniti sva polja!", "Sacuvaj", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String jmbg = jTextFieldZanr.getText();
        
        Autor a = new Autor(-1, jmbg, ime, prezime, ulogovaniRadnik);
        
        ZahtevObjekat zahtev = new ZahtevObjekat();
        zahtev.setOperacija(IOperacije.UBACI_AUTORE);
        zahtev.setParametar(a);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);
        
        OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        
        if(odgovor.getStatus() == IStatus.OK){
            JOptionPane.showMessageDialog(this, "Uspesno sacuvano autor!", "Sacuvaj", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldIme.setText("");
            jTextFieldPrezime.setText("");
            jTextFieldZanr.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno sacuvano autor!", "Sacuvaj", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
         if (jTextFieldIme.getText().isEmpty() || jTextFieldPrezime.getText().isEmpty()
                || jTextFieldZanr.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Morate popuniti sva polja!", "Sacuvaj", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String zanr = jTextFieldZanr.getText();

        autor.setIme(ime);
        autor.setPrezime(prezime);
        autor.setZanr(zanr);
        autor.setRadnik(ulogovaniRadnik);

        ZahtevObjekat zahtev = new ZahtevObjekat();
        zahtev.setOperacija(IOperacije.UPDATE_AUTORA);
        zahtev.setParametar(autor);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);
        
        OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        
        if(odgovor.getStatus() == IStatus.OK){
            JOptionPane.showMessageDialog(this, "Uspesno izmenjen autor", "Izmeni", JOptionPane.INFORMATION_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno izmenjen autor", "Izmeni", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
        jLabelUlogovaniRadnik.setText("Ulogovani radnik: " + ulogovaniRadnik);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelJMBG;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelUlogovaniRadnik;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldZanr;
    // End of variables declaration//GEN-END:variables

}
