/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.knjiga;

import communication.KomunikacijaSaServerom;
import domenn.Autor;
import domenn.Knjiga;
import domenn.Napisana;
import domenn.Radnik;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import konstante.IOperacije;
import konstante.IStatus;
import transfer.OdgovorObjekat;
import transfer.ZahtevObjekat;
import view.model.ModelTabelKnjiga;

/**
 *
 * @author Djordje Vukicevic
 */
public class FrmBrisanjeKnjige extends javax.swing.JPanel {

    private Radnik ulogovaniRadnik;

    /**
     * Creates new form FrmBrisanjeKnjige
     */
    public FrmBrisanjeKnjige() {
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFilter = new javax.swing.ButtonGroup();
        jLabelFilter = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKnjige = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jRadioButtonNaziv = new javax.swing.JRadioButton();
        jRadioButtonGodina = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        jLabelFilter.setText("Filter :");

        jButtonPronadji.setText("Pronadji");
        jButtonPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiActionPerformed(evt);
            }
        });

        jTableKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKnjige);

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jRadioButtonNaziv.setText("Naziv");

        jRadioButtonGodina.setText("Godina");

        jRadioButton1.setText("Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDetalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldFilter)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jRadioButtonNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonGodina)
                .addGap(43, 43, 43)
                .addComponent(jRadioButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPronadji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGodina)
                    .addComponent(jRadioButtonNaziv)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetalji)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonOdustani))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiActionPerformed
        String filter = jTextFieldFilter.getText();
        String nalepi = "";
        
        if(jRadioButtonNaziv.isSelected()){
            nalepi = "WHERE k.naziv LIKE '"+filter+"' ORDER BY k.naziv ASC";
        }
        
        if(jRadioButtonGodina.isSelected()){
            nalepi = "WHERE k.godina LIKE '"+filter+"' ORDER BY k.godina ASC";
        }
        
        if(jRadioButton1.isSelected()){
            nalepi = "WHERE a.prezime LIKE '"+filter+"' ORDER BY a.prezime ASC";
        }
        
        srediTabelu(nalepi);
        JOptionPane.showMessageDialog(this, "Sistem je nasao knjigu po trazenoj vrednosti!", "Pretrazi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonPronadjiActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int red = jTableKnjige.getSelectedRow();
        if(red != -1){
            ModelTabelKnjiga model = (ModelTabelKnjiga) jTableKnjige.getModel();
            Knjiga knjiga = model.vratiKnjigu(red);
            JOptionPane.showMessageDialog(this, "Naziv: "+knjiga.getNaziv()+"\n Cena: "+knjiga.getCena(), "Detalji", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati knjigu!", "Detalji", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
       int red = jTableKnjige.getSelectedRow();
        if(red != -1){
            ModelTabelKnjiga model = (ModelTabelKnjiga) jTableKnjige.getModel();
            Knjiga knjiga = model.vratiKnjigu(red);
            
            Napisana napisana = new Napisana(knjiga, null);
            
            ZahtevObjekat zahtev = new ZahtevObjekat();
            zahtev.setOperacija(IOperacije.IZBRISI_KNJIGU);
            zahtev.setParametar(napisana);
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);
            
            OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            if(odgovor.getStatus()==IStatus.OK){
                JOptionPane.showMessageDialog(this, "Uspesno obrisana knjiga!!", "Obrisi", JOptionPane.INFORMATION_MESSAGE);
                srediTabelu("");
            } else {
                JOptionPane.showMessageDialog(this, "Neuspesno obrisana knjiga!!", "Obrisi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati knjigu!", "Detalji", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFilter;
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPronadji;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonGodina;
    private javax.swing.JRadioButton jRadioButtonNaziv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKnjige;
    private javax.swing.JTextField jTextFieldFilter;
    // End of variables declaration//GEN-END:variables

    public void pripremiFormu() {
        srediTabelu("");
    }

    private void srediTabelu(String nalepi) {
        ZahtevObjekat zahtev = new ZahtevObjekat();
        zahtev.setOperacija(IOperacije.VRATI_KNJIGE);
        zahtev.setParametar(nalepi);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);
        OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<Knjiga> listaKnjiga = (ArrayList<Knjiga>) odgovor.getOdgovor();
        ModelTabelKnjiga model = new ModelTabelKnjiga(listaKnjiga);
        jTableKnjige.setModel(model);
    }
}
