/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.racun;

import communication.KomunikacijaSaServerom;
import domenn.Knjiga;
import domenn.Racun;
import domenn.Radnik;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import konstante.IOperacije;
import konstante.IStatus;
import transfer.OdgovorObjekat;
import transfer.ZahtevObjekat;
import view.model.ModelTabelRacun;

/**
 *
 * @author Djordje Vukicevic
 */
public class FrmKreiranjeRacuna extends javax.swing.JPanel {

    private Radnik ulogovaniRadnik;
    private Racun racun;

    /**
     * Creates new form FrmKreiranjeRacuna
     */
    public FrmKreiranjeRacuna() {
        racun = new Racun();
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovaniRadnik = new javax.swing.JLabel();
        jLabelRacunID = new javax.swing.JLabel();
        jLabelUkupanIznos = new javax.swing.JLabel();
        jTextFieldRacunID = new javax.swing.JTextField();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkaRacuna = new javax.swing.JTable();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonUkloniStavku = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        jLabelUlogovaniRadnik.setText("Ulogovani radnik:");

        jLabelRacunID.setText("Sifra racuna: ");

        jLabelUkupanIznos.setText("Ukupan iznos: ");

        jTextFieldUkupanIznos.setEditable(false);

        jTableStavkaRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkaRacuna);

        jButtonDodajStavku.setText("+");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        jButtonUkloniStavku.setText("-");
        jButtonUkloniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkloniStavkuActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUkloniStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelUkupanIznos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRacunID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldRacunID)
                                .addComponent(jTextFieldUkupanIznos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelUlogovaniRadnik)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelUlogovaniRadnik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRacunID)
                    .addComponent(jTextFieldRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUkupanIznos)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUkloniStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonOdustani))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        ((ModelTabelRacun) jTableStavkaRacuna.getModel()).dodajStavku();
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jButtonUkloniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkloniStavkuActionPerformed
        int selektovaniRed = jTableStavkaRacuna.getSelectedRow();
        ((ModelTabelRacun) jTableStavkaRacuna.getModel()).ukloniStavku(selektovaniRed);
    }//GEN-LAST:event_jButtonUkloniStavkuActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed

        racun.setSifraRacuna(Integer.parseInt(jTextFieldRacunID.getText().trim()));
        racun.setRadnik(ulogovaniRadnik);
        racun.pripremiRacun();
        jTextFieldUkupanIznos.setText("" + racun.getUkupanIznos());

        ZahtevObjekat zahtev = new ZahtevObjekat();
        zahtev.setOperacija(IOperacije.UBACI_RACUN);
        zahtev.setParametar(racun);
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);

        OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        if (odgovor.getStatus() == IStatus.OK) {
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio racun!", "Uspesno cuvanje racuna!", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldRacunID.setText("");
            ModelTabelRacun model = (ModelTabelRacun) jTableStavkaRacuna.getModel();
            model.clear();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti racun!!", "Uspesno cuvanje racuna!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
        jLabelUlogovaniRadnik.setText("Ulogovani radnik: " + ulogovaniRadnik);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonUkloniStavku;
    private javax.swing.JLabel jLabelRacunID;
    private javax.swing.JLabel jLabelUkupanIznos;
    private javax.swing.JLabel jLabelUlogovaniRadnik;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkaRacuna;
    private javax.swing.JTextField jTextFieldRacunID;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        srediTabeluRacun();
    }

    private void srediTabeluRacun() {

        jTableStavkaRacuna.setModel(new ModelTabelRacun(racun));
        JComboBox jComboBoxKnjige = new JComboBox();

        ZahtevObjekat zahtev = new ZahtevObjekat();
        zahtev.setOperacija(IOperacije.VRATI_KNJIGE);
        zahtev.setParametar("");
        KomunikacijaSaServerom.getInstanca().posaljiZahtev(zahtev);

        OdgovorObjekat odgovor = KomunikacijaSaServerom.getInstanca().primiOdgovor();
        ArrayList<Knjiga> listaKnjiga = (ArrayList<Knjiga>) odgovor.getOdgovor();

        for (Knjiga knjiga : listaKnjiga) {
            jComboBoxKnjige.addItem(knjiga);
        }
        TableColumn tcKnjige = jTableStavkaRacuna.getColumnModel().getColumn(0);
        tcKnjige.setCellEditor(new DefaultCellEditor(jComboBoxKnjige));
    }
}
